create table person (
    id int generated by default as identity primary key,
    name varchar unique not null,
    year_of_birth int not null
);

create table book (
    id int generated by default as identity primary key,
    name varchar not null,
    author varchar not null,
    year int not null,
    owned_at timestamp,
    person_id int references person(id) on delete set null
);